library: '~/.local/share/beets/library.db'
directory: '~/Music/'
import:
  write: yes
  copy: yes
  timid: yes
asciify_paths: yes
ui:
  color: yes
plugins: scrub embedart duplicates lyrics
scrub:
  auto: yes
lyrics:
  sources: musixmatch